/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: anoordover@hetcak.nl
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Persoon
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PersoonTests
    {
        // TODO uncomment below to declare an instance variable for Persoon
        //private Persoon instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Persoon
            //instance = new Persoon();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Persoon
        /// </summary>
        [Test]
        public void PersoonInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Persoon
            //Assert.IsInstanceOfType<Persoon> (instance, "variable 'instance' is a Persoon");
        }


        /// <summary>
        /// Test the property 'PersoonId'
        /// </summary>
        [Test]
        public void PersoonIdTest()
        {
            // TODO unit test for the property 'PersoonId'
        }
        /// <summary>
        /// Test the property 'DatumOpdracht'
        /// </summary>
        [Test]
        public void DatumOpdrachtTest()
        {
            // TODO unit test for the property 'DatumOpdracht'
        }
        /// <summary>
        /// Test the property 'Relaties'
        /// </summary>
        [Test]
        public void RelatiesTest()
        {
            // TODO unit test for the property 'Relaties'
        }

    }

}
