/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: anoordover@hetcak.nl
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Relatie
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RelatieTests
    {
        // TODO uncomment below to declare an instance variable for Relatie
        //private Relatie instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Relatie
            //instance = new Relatie();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Relatie
        /// </summary>
        [Test]
        public void RelatieInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Relatie
            //Assert.IsInstanceOfType<Relatie> (instance, "variable 'instance' is a Relatie");
        }


        /// <summary>
        /// Test the property 'PersoonId'
        /// </summary>
        [Test]
        public void PersoonIdTest()
        {
            // TODO unit test for the property 'PersoonId'
        }
        /// <summary>
        /// Test the property 'Ingangsdatum'
        /// </summary>
        [Test]
        public void IngangsdatumTest()
        {
            // TODO unit test for the property 'Ingangsdatum'
        }
        /// <summary>
        /// Test the property 'Einddatum'
        /// </summary>
        [Test]
        public void EinddatumTest()
        {
            // TODO unit test for the property 'Einddatum'
        }

    }

}
