/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: anoordover@hetcak.nl
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRelatieApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Relaties bij een persoon ophalen
        /// </summary>
        /// <remarks>
        /// Geeft de relaties bij een persoon terug
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="persoonId">nummer van de persoon</param>
        /// <param name="opdrachtdatum"></param>
        /// <param name="xCakOrigin"></param>
        /// <param name="xCakCreationdate"></param>
        /// <param name="xCakMessageid"></param>
        /// <param name="xCakRequestid"></param>
        /// <param name="xCakBusinessobject"></param>
        /// <param name="xCakBusinessid"></param>
        /// <param name="xCakUserid"> (optional)</param>
        /// <param name="xCakCallbackurl"> (optional)</param>
        /// <param name="xCakPreviousrequestid"> (optional)</param>
        /// <param name="xCakAuthorization"> (optional)</param>
        /// <param name="xCakInformation"> (optional)</param>
        /// <returns>Persoon</returns>
        Persoon GetRelatiesByPersoonId (int? persoonId, DateTime? opdrachtdatum, string xCakOrigin, DateTime? xCakCreationdate, string xCakMessageid, string xCakRequestid, string xCakBusinessobject, string xCakBusinessid, string xCakUserid = null, string xCakCallbackurl = null, string xCakPreviousrequestid = null, string xCakAuthorization = null, string xCakInformation = null);

        /// <summary>
        /// Relaties bij een persoon ophalen
        /// </summary>
        /// <remarks>
        /// Geeft de relaties bij een persoon terug
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="persoonId">nummer van de persoon</param>
        /// <param name="opdrachtdatum"></param>
        /// <param name="xCakOrigin"></param>
        /// <param name="xCakCreationdate"></param>
        /// <param name="xCakMessageid"></param>
        /// <param name="xCakRequestid"></param>
        /// <param name="xCakBusinessobject"></param>
        /// <param name="xCakBusinessid"></param>
        /// <param name="xCakUserid"> (optional)</param>
        /// <param name="xCakCallbackurl"> (optional)</param>
        /// <param name="xCakPreviousrequestid"> (optional)</param>
        /// <param name="xCakAuthorization"> (optional)</param>
        /// <param name="xCakInformation"> (optional)</param>
        /// <returns>ApiResponse of Persoon</returns>
        ApiResponse<Persoon> GetRelatiesByPersoonIdWithHttpInfo (int? persoonId, DateTime? opdrachtdatum, string xCakOrigin, DateTime? xCakCreationdate, string xCakMessageid, string xCakRequestid, string xCakBusinessobject, string xCakBusinessid, string xCakUserid = null, string xCakCallbackurl = null, string xCakPreviousrequestid = null, string xCakAuthorization = null, string xCakInformation = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Relaties bij een persoon ophalen
        /// </summary>
        /// <remarks>
        /// Geeft de relaties bij een persoon terug
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="persoonId">nummer van de persoon</param>
        /// <param name="opdrachtdatum"></param>
        /// <param name="xCakOrigin"></param>
        /// <param name="xCakCreationdate"></param>
        /// <param name="xCakMessageid"></param>
        /// <param name="xCakRequestid"></param>
        /// <param name="xCakBusinessobject"></param>
        /// <param name="xCakBusinessid"></param>
        /// <param name="xCakUserid"> (optional)</param>
        /// <param name="xCakCallbackurl"> (optional)</param>
        /// <param name="xCakPreviousrequestid"> (optional)</param>
        /// <param name="xCakAuthorization"> (optional)</param>
        /// <param name="xCakInformation"> (optional)</param>
        /// <returns>Task of Persoon</returns>
        System.Threading.Tasks.Task<Persoon> GetRelatiesByPersoonIdAsync (int? persoonId, DateTime? opdrachtdatum, string xCakOrigin, DateTime? xCakCreationdate, string xCakMessageid, string xCakRequestid, string xCakBusinessobject, string xCakBusinessid, string xCakUserid = null, string xCakCallbackurl = null, string xCakPreviousrequestid = null, string xCakAuthorization = null, string xCakInformation = null);

        /// <summary>
        /// Relaties bij een persoon ophalen
        /// </summary>
        /// <remarks>
        /// Geeft de relaties bij een persoon terug
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="persoonId">nummer van de persoon</param>
        /// <param name="opdrachtdatum"></param>
        /// <param name="xCakOrigin"></param>
        /// <param name="xCakCreationdate"></param>
        /// <param name="xCakMessageid"></param>
        /// <param name="xCakRequestid"></param>
        /// <param name="xCakBusinessobject"></param>
        /// <param name="xCakBusinessid"></param>
        /// <param name="xCakUserid"> (optional)</param>
        /// <param name="xCakCallbackurl"> (optional)</param>
        /// <param name="xCakPreviousrequestid"> (optional)</param>
        /// <param name="xCakAuthorization"> (optional)</param>
        /// <param name="xCakInformation"> (optional)</param>
        /// <returns>Task of ApiResponse (Persoon)</returns>
        System.Threading.Tasks.Task<ApiResponse<Persoon>> GetRelatiesByPersoonIdAsyncWithHttpInfo (int? persoonId, DateTime? opdrachtdatum, string xCakOrigin, DateTime? xCakCreationdate, string xCakMessageid, string xCakRequestid, string xCakBusinessobject, string xCakBusinessid, string xCakUserid = null, string xCakCallbackurl = null, string xCakPreviousrequestid = null, string xCakAuthorization = null, string xCakInformation = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class RelatieApi : IRelatieApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="RelatieApi"/> class.
        /// </summary>
        /// <returns></returns>
        public RelatieApi(String basePath)
        {
            this.Configuration = new Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RelatieApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public RelatieApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Relaties bij een persoon ophalen Geeft de relaties bij een persoon terug
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="persoonId">nummer van de persoon</param>
        /// <param name="opdrachtdatum"></param>
        /// <param name="xCakOrigin"></param>
        /// <param name="xCakCreationdate"></param>
        /// <param name="xCakMessageid"></param>
        /// <param name="xCakRequestid"></param>
        /// <param name="xCakBusinessobject"></param>
        /// <param name="xCakBusinessid"></param>
        /// <param name="xCakUserid"> (optional)</param>
        /// <param name="xCakCallbackurl"> (optional)</param>
        /// <param name="xCakPreviousrequestid"> (optional)</param>
        /// <param name="xCakAuthorization"> (optional)</param>
        /// <param name="xCakInformation"> (optional)</param>
        /// <returns>Persoon</returns>
        public Persoon GetRelatiesByPersoonId (int? persoonId, DateTime? opdrachtdatum, string xCakOrigin, DateTime? xCakCreationdate, string xCakMessageid, string xCakRequestid, string xCakBusinessobject, string xCakBusinessid, string xCakUserid = null, string xCakCallbackurl = null, string xCakPreviousrequestid = null, string xCakAuthorization = null, string xCakInformation = null)
        {
             ApiResponse<Persoon> localVarResponse = GetRelatiesByPersoonIdWithHttpInfo(persoonId, opdrachtdatum, xCakOrigin, xCakCreationdate, xCakMessageid, xCakRequestid, xCakBusinessobject, xCakBusinessid, xCakUserid, xCakCallbackurl, xCakPreviousrequestid, xCakAuthorization, xCakInformation);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Relaties bij een persoon ophalen Geeft de relaties bij een persoon terug
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="persoonId">nummer van de persoon</param>
        /// <param name="opdrachtdatum"></param>
        /// <param name="xCakOrigin"></param>
        /// <param name="xCakCreationdate"></param>
        /// <param name="xCakMessageid"></param>
        /// <param name="xCakRequestid"></param>
        /// <param name="xCakBusinessobject"></param>
        /// <param name="xCakBusinessid"></param>
        /// <param name="xCakUserid"> (optional)</param>
        /// <param name="xCakCallbackurl"> (optional)</param>
        /// <param name="xCakPreviousrequestid"> (optional)</param>
        /// <param name="xCakAuthorization"> (optional)</param>
        /// <param name="xCakInformation"> (optional)</param>
        /// <returns>ApiResponse of Persoon</returns>
        public ApiResponse< Persoon > GetRelatiesByPersoonIdWithHttpInfo (int? persoonId, DateTime? opdrachtdatum, string xCakOrigin, DateTime? xCakCreationdate, string xCakMessageid, string xCakRequestid, string xCakBusinessobject, string xCakBusinessid, string xCakUserid = null, string xCakCallbackurl = null, string xCakPreviousrequestid = null, string xCakAuthorization = null, string xCakInformation = null)
        {
            // verify the required parameter 'persoonId' is set
            if (persoonId == null)
                throw new ApiException(400, "Missing required parameter 'persoonId' when calling RelatieApi->GetRelatiesByPersoonId");
            // verify the required parameter 'opdrachtdatum' is set
            if (opdrachtdatum == null)
                throw new ApiException(400, "Missing required parameter 'opdrachtdatum' when calling RelatieApi->GetRelatiesByPersoonId");
            // verify the required parameter 'xCakOrigin' is set
            if (xCakOrigin == null)
                throw new ApiException(400, "Missing required parameter 'xCakOrigin' when calling RelatieApi->GetRelatiesByPersoonId");
            // verify the required parameter 'xCakCreationdate' is set
            if (xCakCreationdate == null)
                throw new ApiException(400, "Missing required parameter 'xCakCreationdate' when calling RelatieApi->GetRelatiesByPersoonId");
            // verify the required parameter 'xCakMessageid' is set
            if (xCakMessageid == null)
                throw new ApiException(400, "Missing required parameter 'xCakMessageid' when calling RelatieApi->GetRelatiesByPersoonId");
            // verify the required parameter 'xCakRequestid' is set
            if (xCakRequestid == null)
                throw new ApiException(400, "Missing required parameter 'xCakRequestid' when calling RelatieApi->GetRelatiesByPersoonId");
            // verify the required parameter 'xCakBusinessobject' is set
            if (xCakBusinessobject == null)
                throw new ApiException(400, "Missing required parameter 'xCakBusinessobject' when calling RelatieApi->GetRelatiesByPersoonId");
            // verify the required parameter 'xCakBusinessid' is set
            if (xCakBusinessid == null)
                throw new ApiException(400, "Missing required parameter 'xCakBusinessid' when calling RelatieApi->GetRelatiesByPersoonId");

            var localVarPath = "/personen/persoon/relaties/{persoonId}/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (persoonId != null) localVarPathParams.Add("persoonId", Configuration.ApiClient.ParameterToString(persoonId)); // path parameter
            if (opdrachtdatum != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "opdrachtdatum", opdrachtdatum)); // query parameter
            if (xCakUserid != null) localVarHeaderParams.Add("x-cak-userid", Configuration.ApiClient.ParameterToString(xCakUserid)); // header parameter
            if (xCakOrigin != null) localVarHeaderParams.Add("x-cak-origin", Configuration.ApiClient.ParameterToString(xCakOrigin)); // header parameter
            if (xCakCallbackurl != null) localVarHeaderParams.Add("x-cak-callbackurl", Configuration.ApiClient.ParameterToString(xCakCallbackurl)); // header parameter
            if (xCakCreationdate != null) localVarHeaderParams.Add("x-cak-creationdate", Configuration.ApiClient.ParameterToString(xCakCreationdate)); // header parameter
            if (xCakMessageid != null) localVarHeaderParams.Add("x-cak-messageid", Configuration.ApiClient.ParameterToString(xCakMessageid)); // header parameter
            if (xCakRequestid != null) localVarHeaderParams.Add("x-cak-requestid", Configuration.ApiClient.ParameterToString(xCakRequestid)); // header parameter
            if (xCakPreviousrequestid != null) localVarHeaderParams.Add("x-cak-previousrequestid", Configuration.ApiClient.ParameterToString(xCakPreviousrequestid)); // header parameter
            if (xCakAuthorization != null) localVarHeaderParams.Add("x-cak-authorization", Configuration.ApiClient.ParameterToString(xCakAuthorization)); // header parameter
            if (xCakBusinessobject != null) localVarHeaderParams.Add("x-cak-businessobject", Configuration.ApiClient.ParameterToString(xCakBusinessobject)); // header parameter
            if (xCakBusinessid != null) localVarHeaderParams.Add("x-cak-businessid", Configuration.ApiClient.ParameterToString(xCakBusinessid)); // header parameter
            if (xCakInformation != null) localVarHeaderParams.Add("x-cak-information", Configuration.ApiClient.ParameterToString(xCakInformation)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetRelatiesByPersoonId", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Persoon>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Persoon) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Persoon)));
        }

        /// <summary>
        /// Relaties bij een persoon ophalen Geeft de relaties bij een persoon terug
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="persoonId">nummer van de persoon</param>
        /// <param name="opdrachtdatum"></param>
        /// <param name="xCakOrigin"></param>
        /// <param name="xCakCreationdate"></param>
        /// <param name="xCakMessageid"></param>
        /// <param name="xCakRequestid"></param>
        /// <param name="xCakBusinessobject"></param>
        /// <param name="xCakBusinessid"></param>
        /// <param name="xCakUserid"> (optional)</param>
        /// <param name="xCakCallbackurl"> (optional)</param>
        /// <param name="xCakPreviousrequestid"> (optional)</param>
        /// <param name="xCakAuthorization"> (optional)</param>
        /// <param name="xCakInformation"> (optional)</param>
        /// <returns>Task of Persoon</returns>
        public async System.Threading.Tasks.Task<Persoon> GetRelatiesByPersoonIdAsync (int? persoonId, DateTime? opdrachtdatum, string xCakOrigin, DateTime? xCakCreationdate, string xCakMessageid, string xCakRequestid, string xCakBusinessobject, string xCakBusinessid, string xCakUserid = null, string xCakCallbackurl = null, string xCakPreviousrequestid = null, string xCakAuthorization = null, string xCakInformation = null)
        {
             ApiResponse<Persoon> localVarResponse = await GetRelatiesByPersoonIdAsyncWithHttpInfo(persoonId, opdrachtdatum, xCakOrigin, xCakCreationdate, xCakMessageid, xCakRequestid, xCakBusinessobject, xCakBusinessid, xCakUserid, xCakCallbackurl, xCakPreviousrequestid, xCakAuthorization, xCakInformation);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Relaties bij een persoon ophalen Geeft de relaties bij een persoon terug
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="persoonId">nummer van de persoon</param>
        /// <param name="opdrachtdatum"></param>
        /// <param name="xCakOrigin"></param>
        /// <param name="xCakCreationdate"></param>
        /// <param name="xCakMessageid"></param>
        /// <param name="xCakRequestid"></param>
        /// <param name="xCakBusinessobject"></param>
        /// <param name="xCakBusinessid"></param>
        /// <param name="xCakUserid"> (optional)</param>
        /// <param name="xCakCallbackurl"> (optional)</param>
        /// <param name="xCakPreviousrequestid"> (optional)</param>
        /// <param name="xCakAuthorization"> (optional)</param>
        /// <param name="xCakInformation"> (optional)</param>
        /// <returns>Task of ApiResponse (Persoon)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Persoon>> GetRelatiesByPersoonIdAsyncWithHttpInfo (int? persoonId, DateTime? opdrachtdatum, string xCakOrigin, DateTime? xCakCreationdate, string xCakMessageid, string xCakRequestid, string xCakBusinessobject, string xCakBusinessid, string xCakUserid = null, string xCakCallbackurl = null, string xCakPreviousrequestid = null, string xCakAuthorization = null, string xCakInformation = null)
        {
            // verify the required parameter 'persoonId' is set
            if (persoonId == null)
                throw new ApiException(400, "Missing required parameter 'persoonId' when calling RelatieApi->GetRelatiesByPersoonId");
            // verify the required parameter 'opdrachtdatum' is set
            if (opdrachtdatum == null)
                throw new ApiException(400, "Missing required parameter 'opdrachtdatum' when calling RelatieApi->GetRelatiesByPersoonId");
            // verify the required parameter 'xCakOrigin' is set
            if (xCakOrigin == null)
                throw new ApiException(400, "Missing required parameter 'xCakOrigin' when calling RelatieApi->GetRelatiesByPersoonId");
            // verify the required parameter 'xCakCreationdate' is set
            if (xCakCreationdate == null)
                throw new ApiException(400, "Missing required parameter 'xCakCreationdate' when calling RelatieApi->GetRelatiesByPersoonId");
            // verify the required parameter 'xCakMessageid' is set
            if (xCakMessageid == null)
                throw new ApiException(400, "Missing required parameter 'xCakMessageid' when calling RelatieApi->GetRelatiesByPersoonId");
            // verify the required parameter 'xCakRequestid' is set
            if (xCakRequestid == null)
                throw new ApiException(400, "Missing required parameter 'xCakRequestid' when calling RelatieApi->GetRelatiesByPersoonId");
            // verify the required parameter 'xCakBusinessobject' is set
            if (xCakBusinessobject == null)
                throw new ApiException(400, "Missing required parameter 'xCakBusinessobject' when calling RelatieApi->GetRelatiesByPersoonId");
            // verify the required parameter 'xCakBusinessid' is set
            if (xCakBusinessid == null)
                throw new ApiException(400, "Missing required parameter 'xCakBusinessid' when calling RelatieApi->GetRelatiesByPersoonId");

            var localVarPath = "/personen/persoon/relaties/{persoonId}/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (persoonId != null) localVarPathParams.Add("persoonId", Configuration.ApiClient.ParameterToString(persoonId)); // path parameter
            if (opdrachtdatum != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "opdrachtdatum", opdrachtdatum)); // query parameter
            if (xCakUserid != null) localVarHeaderParams.Add("x-cak-userid", Configuration.ApiClient.ParameterToString(xCakUserid)); // header parameter
            if (xCakOrigin != null) localVarHeaderParams.Add("x-cak-origin", Configuration.ApiClient.ParameterToString(xCakOrigin)); // header parameter
            if (xCakCallbackurl != null) localVarHeaderParams.Add("x-cak-callbackurl", Configuration.ApiClient.ParameterToString(xCakCallbackurl)); // header parameter
            if (xCakCreationdate != null) localVarHeaderParams.Add("x-cak-creationdate", Configuration.ApiClient.ParameterToString(xCakCreationdate)); // header parameter
            if (xCakMessageid != null) localVarHeaderParams.Add("x-cak-messageid", Configuration.ApiClient.ParameterToString(xCakMessageid)); // header parameter
            if (xCakRequestid != null) localVarHeaderParams.Add("x-cak-requestid", Configuration.ApiClient.ParameterToString(xCakRequestid)); // header parameter
            if (xCakPreviousrequestid != null) localVarHeaderParams.Add("x-cak-previousrequestid", Configuration.ApiClient.ParameterToString(xCakPreviousrequestid)); // header parameter
            if (xCakAuthorization != null) localVarHeaderParams.Add("x-cak-authorization", Configuration.ApiClient.ParameterToString(xCakAuthorization)); // header parameter
            if (xCakBusinessobject != null) localVarHeaderParams.Add("x-cak-businessobject", Configuration.ApiClient.ParameterToString(xCakBusinessobject)); // header parameter
            if (xCakBusinessid != null) localVarHeaderParams.Add("x-cak-businessid", Configuration.ApiClient.ParameterToString(xCakBusinessid)); // header parameter
            if (xCakInformation != null) localVarHeaderParams.Add("x-cak-information", Configuration.ApiClient.ParameterToString(xCakInformation)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetRelatiesByPersoonId", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Persoon>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Persoon) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Persoon)));
        }

    }
}
