/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: anoordover@hetcak.nl
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Relatie
    /// </summary>
    [DataContract]
    public partial class Relatie :  IEquatable<Relatie>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Relatie" /> class.
        /// </summary>
        /// <param name="PersoonId">PersoonId.</param>
        /// <param name="Ingangsdatum">Ingangsdatum.</param>
        /// <param name="Einddatum">Einddatum.</param>
        public Relatie(int? PersoonId = default(int?), DateTime? Ingangsdatum = default(DateTime?), DateTime? Einddatum = default(DateTime?))
        {
            this.PersoonId = PersoonId;
            this.Ingangsdatum = Ingangsdatum;
            this.Einddatum = Einddatum;
        }
        
        /// <summary>
        /// Gets or Sets PersoonId
        /// </summary>
        [DataMember(Name="PersoonId", EmitDefaultValue=false)]
        public int? PersoonId { get; set; }

        /// <summary>
        /// Gets or Sets Ingangsdatum
        /// </summary>
        [DataMember(Name="Ingangsdatum", EmitDefaultValue=false)]
        [JsonConverter(typeof(SwaggerDateConverter))]
        public DateTime? Ingangsdatum { get; set; }

        /// <summary>
        /// Gets or Sets Einddatum
        /// </summary>
        [DataMember(Name="Einddatum", EmitDefaultValue=false)]
        [JsonConverter(typeof(SwaggerDateConverter))]
        public DateTime? Einddatum { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Relatie {\n");
            sb.Append("  PersoonId: ").Append(PersoonId).Append("\n");
            sb.Append("  Ingangsdatum: ").Append(Ingangsdatum).Append("\n");
            sb.Append("  Einddatum: ").Append(Einddatum).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Relatie);
        }

        /// <summary>
        /// Returns true if Relatie instances are equal
        /// </summary>
        /// <param name="input">Instance of Relatie to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Relatie input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.PersoonId == input.PersoonId ||
                    (this.PersoonId != null &&
                    this.PersoonId.Equals(input.PersoonId))
                ) && 
                (
                    this.Ingangsdatum == input.Ingangsdatum ||
                    (this.Ingangsdatum != null &&
                    this.Ingangsdatum.Equals(input.Ingangsdatum))
                ) && 
                (
                    this.Einddatum == input.Einddatum ||
                    (this.Einddatum != null &&
                    this.Einddatum.Equals(input.Einddatum))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PersoonId != null)
                    hashCode = hashCode * 59 + this.PersoonId.GetHashCode();
                if (this.Ingangsdatum != null)
                    hashCode = hashCode * 59 + this.Ingangsdatum.GetHashCode();
                if (this.Einddatum != null)
                    hashCode = hashCode * 59 + this.Einddatum.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
